config/routes.rb
MySchool::Application.routes.draw do
  resource :school, only: [:show, :edit, :update]
  resources :school_years do
    post :set, on: :member
  end

  resources :teachers
  resources :students
  resources :parents

  resources :klasses, shallow: true do
    resources :students, controller: 'klass_students', only: :index
    resources :parents, controller: 'klass_parents', only: :index
    resources :teachers, controller: 'klass_teachers', only: :index
    resources :birthdays, controller: 'klass_birthdays', only: :index
    resources :courses
    resources :tests
  end

  root 'teachers#index'
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school, inverse_of: :teachers
  has_many :courses, inverse_of: :teachers
  has_many :klasses, -> { uniq.reorder(:name) }, through: :courses
  has_many :students, -> { uniq.reorder(:last_name, :first_name) }, through: :courses
  has_many :tests, inverse_of: :teacher
  validates :school_id, :first_name, :last_name, presence: true
  validates :email, email: { allow_blank: true }
  localize_field :date_of_birth
  scope :by_name, -> { order(:last_name, :first_name) }
  default_scope { by_name }

  def name
    "#{first_name} #{last_name}"
  end

  def klasses_in(school_year)
    @klasses_in_school_year ||= klasses.where(school_year_id: school_year.id)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  def index
    @teachers = current_school.teachers
  end

  # GET /teachers/1
  def show
  end

  # GET /teachers/new
  def new
    @teacher = current_school.teachers.build
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  def create
    @teacher = current_school.teachers.build(teacher_params)

    if @teacher.save
      redirect_to @teacher, notice: 'Lehrer wurde erfolgreich erstellt.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /teachers/1
  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: 'Lehrer wurde erfolgreich aktualisiert.'
    else
      render action: 'edit'
    end
  end

  # DELETE /teachers/1
  def destroy
    @teacher.destroy
    redirect_to teachers_url, notice: 'Lehrer wurde erfolgreich gelöscht.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = current_school.teachers.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def teacher_params
      params.require(:teacher).permit(:last_name, :first_name, :form_of_address, :gender, :date_of_birth, :email, :shorthand_symbol)
    end
end

app/views/teachers/_form.html.slim
= form_for @teacher do |f|
  = render 'error_messages', target: @teacher

  .field
    = f.label :last_name
    = f.text_field :last_name, autofocus: @teacher.new_record?
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :form_of_address
    = f.text_field :form_of_address
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :date_of_birth
    .input-group
      span class='input-group-addon' = icon_tag(:calendar)
      = f.text_field :date_of_birth, class: 'date', value: @teacher.date_of_birth
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :shorthand_symbol
    = f.text_field :shorthand_symbol

  .actions = f.submit

app/views/teachers/edit.html.slim
h1 Lehrer bearbeiten

== render 'form'

app/views/teachers/index.html.slim
h1
  ' Lehrer
  small = current_school.name

table class='table table-striped'
  tr
    th = Teacher.human_attribute_name(:last_name)
    th = Teacher.human_attribute_name(:first_name)
    th = Teacher.human_attribute_name(:form_of_address)
    th = Teacher.human_attribute_name(:gender)
    th = Teacher.human_attribute_name(:date_of_birth)
    th = Teacher.human_attribute_name(:email)
    th = Teacher.human_attribute_name(:shorthand_symbol)
    th = Teacher.human_attribute_name(:klass_names)
    th

  - @teachers.each do |teacher|
    - teacher = teacher.decorate

    tr
      td = teacher.last_name
      td = teacher.first_name
      td = teacher.form_of_address
      td = teacher.gender
      td = teacher.date_of_birth
      td = teacher.email
      td = teacher.shorthand_symbol
      td = teacher.klass_names_in(current_school_year)
      td class='actions'
        = link_to 'Anzeigen', teacher
        = link_to 'Bearbeiten', edit_teacher_path(teacher)
        = link_to 'Löschen', teacher, data: { confirm: 'Sind Sie sicher?' }, :method => :delete

= link_to 'Neuer Lehrer', new_teacher_path, class: 'btn btn-default'

app/views/teachers/new.html.slim
h1 Neuer Lehrer

== render 'form'

app/views/teachers/show.html.slim
p
  strong Last name:
  = @teacher.last_name
p
  strong First name:
  = @teacher.first_name
p
  strong Form of address:
  = @teacher.form_of_address
p
  strong Gender:
  = @teacher.gender
p
  strong Date of birth:
  = @teacher.date_of_birth
p
  strong Email:
  = @teacher.email
p
  strong Shorthand symbol:
  = @teacher.shorthand_symbol

=> link_to 'Bearbeiten', edit_teacher_path(@teacher)
'|
= link_to 'Zurück', teachers_path