config/routes.rb
MySchool::Application.routes.draw do
  resource :school, only: [:show, :edit, :update]
  resources :school_years do
    post :set, on: :member
  end

  resources :teachers
  resources :students
  resources :parents

  resources :klasses, shallow: true do
    resources :students, controller: 'klass_students', only: :index
    resources :parents, controller: 'klass_parents', only: :index
    resources :teachers, controller: 'klass_teachers', only: :index
    resources :birthdays, controller: 'klass_birthdays', only: :index
    resources :courses
    resources :tests
  end

  root 'teachers#index'
end

app/models/school_year.rb
class SchoolYear < ActiveRecord::Base
  belongs_to :school, inverse_of: :school_years
  has_many :klasses, inverse_of: :school_year
  has_many :tests, through: :klasses
  has_many :courses, inverse_of: :school_year
  validates :school_id, :name, :start_date, :end_date, presence: true
  localize_fields :start_date, :end_date
  scope :by_date, ->(direction=:asc) { order(start_date: direction) }
  default_scope { by_date }

  def date_range
    self[:start_date]..self[:end_date]
  end

  def weekdays
    date_range.to_a.select { |day| day.wday.in?(1..5)  }
  end

  def weekend_days
    date_range.to_a.select { |day| day.wday.in?([0,6])  }
  end
end

app/controllers/school_years_controller.rb
class SchoolYearsController < ApplicationController
  before_action :set_school_year, only: [:show, :edit, :update, :destroy, :set]

  # GET /school_years
  def index
    @school_years = current_school.school_years
  end

  # GET /school_years/1
  def show
  end

  # GET /school_years/new
  def new
    @school_year = current_school.school_years.build
  end

  # GET /school_years/1/edit
  def edit
  end

  # POST /school_years
  def create
    @school_year = current_school.school_years.build(school_year_params)

    if @school_year.save
      redirect_to @school_year, notice: 'Schuljahr wurde erfolgreich erstellt.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /school_years/1
  def update
    if @school_year.update(school_year_params)
      redirect_to @school_year, notice: 'Schuljahr wurde erfolgreich aktualisiert.'
    else
      render action: 'edit'
    end
  end

  # DELETE /school_years/1
  def destroy
    @school_year.destroy
    redirect_to school_years_url, notice: 'Schuljahr wurde erfolgreich gelöscht.'
  end

  # POST /school_years/1/set
  # Set current school year
  def set
    if @school_year.id == current_school.default_school_year_id
      # default school year is set
      session.delete(:current_school_year_id)
    else
      # store school year id in session
      session[:current_school_year_id] = @school_year.id
    end

    redirect_to :back
    rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_year
      @school_year = current_school.school_years.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def school_year_params
      params.require(:school_year).permit(:name, :start_date, :end_date)
    end
end

app/views/school_years/_form.html.slim
= form_for @school_year do |f|
  = render 'error_messages', target: @school_year

  .field
    = f.label :name
    = f.text_field :name, autofocus: @school_year.new_record?

  - %w(start_date end_date).each do |field|
    .field
      = f.label field
      .input-group
        span class='input-group-addon' = icon_tag(:calendar)
        = f.text_field field, class: 'date', value: @school_year.send(field)

  .actions = f.submit

app/views/school_years/edit.html.slim
h1 Bearbeite Schuljahr

== render 'form'

app/views/school_years/index.html.slim
h1 Schuljahre

p In den #{ link_to 'Schuleinstellungen', school_path } können Sie das "Voreingestellte Schuljahr" ändern.

table class='table table-striped'
  tr
    th = SchoolYear.human_attribute_name(:name)
    th = SchoolYear.human_attribute_name(:start_date)
    th = SchoolYear.human_attribute_name(:end_date)
    th

  - @school_years.each do |school_year|
    tr
      td
        = link_to school_year do
          => school_year.name
        = '(' + School.human_attribute_name(:default_school_year) + ')' if school_year.id == current_school.default_school_year_id
      td = school_year.start_date
      td = school_year.end_date
      td class='actions'
        = link_to 'Bearbeiten', edit_school_year_path(school_year)
        = link_to 'Löschen', school_year, data: { confirm: 'Sind Sie sicher?' }, :method => :delete

= link_to 'Neues Schuljahr', new_school_year_path, class: 'btn btn-default'

app/views/school_years/new.html.slim
h1 Neues Schuljahr

== render 'form'

app/views/school_years/show.html.slim
/ show school
- @school_year = @school_year.decorate

h1
  ' Schuljahr
  small = link_to 'Bearbeiten', edit_school_year_path(@school_year)

table class='table table-striped table-bordered'
  tbody
    - %w(name start_date end_date).each do |field|
      tr
        td: b = SchoolYear.human_attribute_name(field)
        td = @school_year.send(field)

= link_to 'Zurück', school_years_path