config/routes.rb
MySchool::Application.routes.draw do
  resource :school, only: [:show, :edit, :update]
  resources :school_years do
    post :set, on: :member
  end

  resources :teachers
  resources :students
  resources :parents

  resources :klasses, shallow: true do
    resources :students, controller: 'klass_students', only: :index
    resources :parents, controller: 'klass_parents', only: :index
    resources :teachers, controller: 'klass_teachers', only: :index
    resources :birthdays, controller: 'klass_birthdays', only: :index
    resources :courses
    resources :tests
  end

  root 'teachers#index'
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :school, inverse_of: :parents
  has_many :student_parents
  has_many :students, through: :student_parents
  # Reordering removes the default scope (ordering) from students
  has_many :klasses, -> { uniq.reorder(:name) }, through: :students
  validates :school_id, :last_name, :first_name, presence: true
  localize_field :date_of_birth
  scope :by_name, -> { order(:last_name, :first_name) }
  default_scope { by_name }

  def name
    "#{first_name} #{last_name}"
  end

  def klasses_in(school_year)
    @klasses_in_school_year ||= klasses.where(school_year_id: school_year.id)
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  def index
    @parents = current_school.parents
  end

  # GET /parents/1
  def show
  end

  # GET /parents/new
  def new
    @parent = current_school.parents.build
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  def create
    @parent = current_school.parents.build(parent_params)

    if @parent.save
      redirect_to @parent, notice: 'Elternteil wurde erfolgreich erstellt.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /parents/1
  def update
    if @parent.update(parent_params)
      redirect_to @parent, notice: 'Elternteil wurde erfolgreich aktualisiert.'
    else
      render action: 'edit'
    end
  end

  # DELETE /parents/1
  def destroy
    @parent.destroy
    redirect_to parents_url, notice: 'Elternteil wurde erfolgreich gelöscht.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = current_school.parents.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def parent_params
      params.require(:parent).permit(:last_name, :first_name, :form_of_address, :gender, :date_of_birth, :email)
    end
end

app/views/parents/_form.html.slim
= form_for @parent do |f|
  = render 'error_messages', target: @parent

  .field
    = f.label :last_name
    = f.text_field :last_name, autofocus: @parent.new_record?
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :form_of_address
    = f.text_field :form_of_address
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :date_of_birth
    .input-group
      span class='input-group-addon' = icon_tag(:calendar)
      = f.text_field :date_of_birth, class: 'date', value: @parent.date_of_birth
  .field
    = f.label :email
    = f.text_field :email

  .actions = f.submit

app/views/parents/edit.html.slim
h1 Bearbeite Elternteil

== render 'form'

app/views/parents/index.html.slim
h1 Eltern

table class='table table-striped'
  tr
    th = Parent.human_attribute_name(:last_name)
    th = Parent.human_attribute_name(:first_name)
    th = Parent.human_attribute_name(:form_of_address)
    th = Parent.human_attribute_name(:gender)
    th = Parent.human_attribute_name(:date_of_birth)
    th = Parent.human_attribute_name(:email)
    th = Parent.human_attribute_name(:klass_names)
    th

  - @parents.each do |parent|
    - parent = parent.decorate

    tr
      td = parent.last_name
      td = parent.first_name
      td = parent.form_of_address
      td = parent.gender
      td = parent.date_of_birth
      td = parent.email
      td = parent.klass_names_in(current_school_year)
      td class='actions'
        = link_to 'Anzeigen', parent
        = link_to 'Bearbeiten', edit_parent_path(parent)
        = link_to 'Löschen', parent, data: { confirm: 'Sind Sie sicher?' }, :method => :delete

= link_to 'Neues Elternteil', new_parent_path, class: 'btn btn-default'

app/views/parents/new.html.slim
h1 Neues Elternteil

== render 'form'

app/views/parents/show.html.slim
p#notice = notice

p
  strong School:
  = @parent.school
p
  strong Last name:
  = @parent.last_name
p
  strong First name:
  = @parent.first_name
p
  strong Form of address:
  = @parent.form_of_address
p
  strong Gender:
  = @parent.gender
p
  strong Date of birth:
  = @parent.date_of_birth
p
  strong Email:
  = @parent.email

= link_to 'Edit', edit_parent_path(@parent)
'|
= link_to 'Back', parents_path